name: Opentf CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

defaults:
  run:
    shell: sh -eux {0}

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

jobs:
  opentf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.ACCESS_KEY }}
          aws-secret-access-key: ${{ env.SECRET_KEY }}
          aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Prepare OpenTofu
        uses: opentofu/setup-opentofu@v1

      - run: pwd

      - run: ls

      - run: tofu init

      - id: plan
        run: tofu plan -no-color

      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}

#      - name: Download the tofu source
#        uses: actions/checkout@v4
#        with:
#          repository: opentofu/opentofu
#          path: opentofu
#
#      - name: Install tofu tooling
#        uses: actions/setup-go@v4
#        with:
#          go-version-file: opentofu/go.mod
#          cache-dependency-path: opentofu/go.sum
#
#      - name: Prepare the tofu command
#        working-directory: opentofu
#        run: |
#          go build -ldflags "-w -s -X 'github.com/opentofu/opentofu/version.dev=no'" -o bin/tofu .
#          echo $(pwd)/bin >> $GITHUB_PATH
#
#      - name: Initialize opentf
#        run: opentf init -lock=false
#
#      - name: Validate opentf
#        run: opentf validate
#
#      - name: Plan opentf
#        run: opentf plan -var-file="./dev.tfvars" -var "access_key=${ACCESS_KEY}" -var "secret_key=${SECRET_KEY}" -lock=false
